### PR TITLE
test using loopback rather than internet accessible address

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
Originally https://github.com/gisle/http-daemon/pull/2 and https://github.com/libwww-perl/HTTP-Daemon/pull/4

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @michal-josef-spacek! The following will get the build to pass:

```diff
 git diff
diff --git a/Changes b/Changes
index 2a1c241..2ea8b35 100644
--- a/Changes
+++ b/Changes
@@ -1,6 +1,8 @@
 Revision history for HTTP-Daemon

 {{$NEXT}}
+    - test using loopback rather than internet accessible address (GH#52)
+      (Michal Josef Špaček)

 6.13      2022-02-09 20:39:12Z
   - Bump minimum IO::Socket::IP version to 0.32 (GH#50) (Olaf Alders)
  ```

**Comment by oalders** [comment]
@michal-josef-spacek could you rebase and force-push? There will be a merge conflict in `Changes`, I apologize for that. ☹️

**Comment by michal-josef-spacek** [comment]
@oalders Done, thanks.

**Comment by skaji** [comment]
A lot of things have changed since 2015.

To support various platforms as much as possible, we should not specify `LocalAddr` to HTTP::Daemon->new.

**Comment by michal-josef-spacek** [comment]
@skaji Do you mean rewrite from LocalAddr to LocalHost constructor parameter?
I am looking to tests in IO::Socket::IP and there is it.
It's working too.
(LocalAddr is direct synonymum to LocalHost)

**Comment by skaji** [comment]
@michal-josef-spacek  Sorry, I was wrong. Please ignore my previous comment.

**Comment by michal-josef-spacek** [comment]
@skaji Only thing is, that this configuration is set for IPv4 only. If IPv4 doesn't present test doesn't run. 
This fixes LocalHost => 'localhost', but i don't know if this setting is portable.

from man perlport:
Don't assume that you can reach yourself or any node by the name 'localhost'. The same goes for '127.0.0.1'. You will have to try both.

**Comment by oalders** [comment]
Thanks @michal-josef-spacek!

**Pull request merged**
